# Project information
site_name: mkdocs-mlflow-template
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: Surajit Das
site_description: >-
  DESCRIPTION

# Repository
repo_name: SurajitDas1991/mkdocs-mlflow-template
repo_url: https://github.com/SurajitDas1991/mkdocs-mlflow-template

# Configuration
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SurajitDas1991
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/surajit-das-0306aa66/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark


plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/SurajitDas1991"  target="_blank" rel="noopener">Surajit Das</a>
